<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>16.1. Exceptions &#8212; Introduction to Programming in C#  documentation</title>
    <link rel="stylesheet" href="../../_static/pygments.css" type="text/css" />
    <link rel="stylesheet" href="../../_static/bootstrap-sphinx.css" type="text/css" />
    <link rel="stylesheet" type="text/css" href="../../_static/fa/css/all.css" />
    <link rel="stylesheet" type="text/css" href="../../_static/css/launchcode.css" />
    <link rel="stylesheet" type="text/css" href="../../_static/css/site.css" />
    <script id="documentation_options" data-url_root="../../" src="../../_static/documentation_options.js"></script>
    <script src="../../_static/jquery.js"></script>
    <script src="../../_static/underscore.js"></script>
    <script src="../../_static/doctools.js"></script>
    <script src="../../_static/language_data.js"></script>
    <link rel="index" title="Index" href="../../genindex.html" />
    <link rel="search" title="Search" href="../../search.html" />
    <link rel="next" title="16.2. Handling Exceptions" href="handling.html" />
    <link rel="prev" title="16. Rules to the Exceptions" href="index.html" />
<meta charset='utf-8'>
<meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>
<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1'>
<meta name="apple-mobile-web-app-capable" content="yes">
<script type="text/javascript" src="../../_static/js/jquery-1.12.4.min.js"></script>
<script type="text/javascript" src="../../_static/js/jquery-fix.js"></script>
<script type="text/javascript" src="../../_static/bootstrap-3.4.1/js/bootstrap.min.js"></script>
<script type="text/javascript" src="../../_static/bootstrap-sphinx.js"></script>

  </head><body class="body-bc">

<div id="navbar" class="navbar navbar-default navbar-fixed-top">
   <div class="container">
     <div class="navbar-header">
       <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       <a class="navbar-brand" href="../../index.html"><span><img src="../../_static/lc-ed-logo.png" alt="LaunchCode logo"></span>
       </a>
       <span class="navbar-text navbar-version pull-left"><b></b></span>
     </div>

       <div class="collapse navbar-collapse nav-collapse">
         <ul class="nav navbar-nav">
           
           
             
           
           
           
           
           
         </ul>

         
           
<form class="navbar-form navbar-right" action="../../search.html" method="get">
 <div class="form-group">
    <label for="q" class="searchLabel">Search</label>
    <input type="text" name="q" class="form-control" />
 </div>
  <input type="hidden" name="check_keywords" value="yes" />
  <input type="hidden" name="area" value="default" />
</form>
         
       </div>
   </div>
 </div>

<ol class="breadcrumb container">
    <li><a href="../../index.html">Contents</a></li>
    <li><a href="index.html"><span class="section-number">16. </span>Rules to the Exceptions</a></li>
    <li class="active"><span class="section-number">16.1. </span>Exceptions</li>
</ol>



<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1 content " role="main">

    
  <div class="section" id="exceptions">
<span id="index-0"></span><h1><span class="section-number">16.1. </span>Exceptions<a class="headerlink" href="#exceptions" title="Permalink to this headline">¶</a></h1>
<p id="index-1">Errors are a part of coding. Occasionally, we make mistakes as programmers.
However, we are always trying to fix those mistakes by reading different
resources, examining a list of error messages (also called the <strong>stacktrace</strong>),
or asking for help.</p>
<p>Earlier in this course, we learned about two different types of errors: compiler
and logic. A logic error is when your program executes without breaking, but
doesn’t behave the way you thought it would. These logic errors usually require
you to consider how you are going about solving the issue to resolve. Compiler
errors are when your program does not run correctly, and an exception is
raised.</p>
<p>Maybe you see the term “exception” and instinctively groan or roll your eyes? Isn’t programming
only enjoyable when it works? While it would be nice if our code ran perfectly every time,
exceptions are a key component of a healthy codebase. When an exception arises, we, as programmers,
can use the info to debug our code. For our fellow programmers, the exceptions we provide give them
necessary intel on how our app runs and is meant to be used.</p>
<p>Like most programming languages, C# includes exceptions and exception handling tooling.
Some exception objects are provided by .NET itself. Other exception objects we may get from
external C# libraries. We may even write these objects ourselves.</p>
<p><strong>Exceptions</strong> in C# are objects derived from the <code class="docutils literal notranslate"><span class="pre">System.Exception</span></code> class.
You see exception objects at runtime when some event takes place outside of the expected flow of our code.
When you want to explicitly call an exception in your code, you do so
with the <strong>throw</strong> keyword.</p>
<div class="section" id="when-exceptions-arise">
<span id="index-2"></span><h2><span class="section-number">16.1.1. </span>When Exceptions Arise<a class="headerlink" href="#when-exceptions-arise" title="Permalink to this headline">¶</a></h2>
<p>You may have seen exceptions in C# or another programming language already, perhaps in one
of these scenarios:</p>
<ul class="simple">
<li>Failure to connect to services external to your application, such as a database or Application Program Interface (API).</li>
<li>Failure to read or write to or from a file.</li>
<li>Failure to convert data, such as trying to convert something like <code class="docutils literal notranslate"><span class="pre">&quot;dog&quot;</span></code> to an <code class="docutils literal notranslate"><span class="pre">int</span></code> type.</li>
<li>Failure to reach an actual object.</li>
</ul>
<div class="admonition-note admonition">
<p class="first admonition-title"><i class="fas fa-sticky-note" aria-hidden="true"></i>Note</p>
<p class="last">This last scenario is a <strong>null pointer</strong>. This is an object reference that doesn’t actually
contain an object.</p>
</div>
<p>Let’s look at an example where exceptions would help with the overall output of code.</p>
<p>Here is a block of code that prints out a Fahrenheit temperature value.</p>
<div class="highlight-c# notranslate"><table class="highlighttable"><tr><td class="linenos"><div class="linenodiv"><pre> 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="k">class</span> <span class="nc">Program</span>
<span class="p">{</span>
   <span class="k">static</span> <span class="k">void</span> <span class="nf">Main</span><span class="p">(</span><span class="kt">string</span><span class="p">[]</span> <span class="n">args</span><span class="p">)</span>
   <span class="p">{</span>
      <span class="n">Console</span><span class="p">.</span><span class="n">WriteLine</span><span class="p">(</span><span class="s">&quot;Please enter a Fahrenheit temperature value&quot;</span><span class="p">);</span>
      <span class="kt">string</span> <span class="n">inputValue</span> <span class="p">=</span> <span class="n">Console</span><span class="p">.</span><span class="n">ReadLine</span><span class="p">();</span>
      <span class="kt">double</span> <span class="n">inputTemp</span> <span class="p">=</span> <span class="n">Double</span><span class="p">.</span><span class="n">Parse</span><span class="p">(</span><span class="n">inputValue</span><span class="p">);</span>

      <span class="c1">//Test 1: userTemp set to 73</span>
      <span class="n">Temperature</span> <span class="n">userTemp</span> <span class="p">=</span> <span class="k">new</span> <span class="n">Temperature</span><span class="p">(</span><span class="n">inputTemp</span><span class="p">);</span>

      <span class="c1">//re-run program</span>

      <span class="c1">//Test 2: userTemp set to -8200</span>
      <span class="n">Temperature</span> <span class="n">userTemp</span> <span class="p">=</span> <span class="k">new</span> <span class="n">Temperature</span><span class="p">(</span><span class="n">inputTemp</span><span class="p">);</span>

   <span class="p">}</span>
<span class="p">}</span>

<span class="k">public</span> <span class="k">class</span> <span class="nc">Temperature</span>
<span class="p">{</span>

   <span class="k">public</span> <span class="nf">Temperature</span><span class="p">(</span><span class="kt">double</span> <span class="n">fahrenheit</span><span class="p">)</span>
   <span class="p">{</span>
      <span class="n">Console</span><span class="p">.</span><span class="n">WriteLine</span><span class="p">(</span><span class="s">&quot;You entered &quot;</span> <span class="p">+</span> <span class="n">fahrenheit</span> <span class="p">+</span> <span class="s">&quot; degrees F.&quot;</span><span class="p">);</span>
   <span class="p">}</span>
<span class="p">}</span>
</pre></div>
</td></tr></table></div>
<p>It is very simple.  Provide the value, print sentence.  Great.
However, Fahrenheit cannot go beyond -459.67 degrees.  That is absolute zero, the equivilant to 0 degrees Kelvin.</p>
<p>So, why would we want a user to be able to go past absolute zero in our program, when it is not physically possible?
No one wants invalid data.
This would be a good place to throw an exception.</p>
</div>
<div class="section" id="throwing-an-exception">
<h2><span class="section-number">16.1.2. </span>Throwing An Exception<a class="headerlink" href="#throwing-an-exception" title="Permalink to this headline">¶</a></h2>
<p id="index-3">In most programming languages, when the compiler or interpreter encounters code it doesn’t know how to handle, it
<strong>throws</strong> an exception.
This is how the compiler notifies the programmer that something has gone wrong.
Throwing an exception is also known as <em>raising</em> an exception.</p>
<p>C# gives us the ability to raise exceptions using the <code class="docutils literal notranslate"><span class="pre">throw</span></code> statement by using the <code class="docutils literal notranslate"><span class="pre">System.Exception</span></code> class.
One reason to throw an exception is if your code is being used in an unexpected way.</p>
<p>In our temperature app, we don’t want the user to go past absolute zero, so we can thrown an exception that will inform us of the issue.
The <code class="docutils literal notranslate"><span class="pre">ArgumentOutOfRangeException</span></code> will be a good fit for our exception.</p>
<p>The question is where to validate our data?
It would make sense to have an issue arrise at instantiation of a new <code class="docutils literal notranslate"><span class="pre">Temperature</span></code> object.
That would prevent any objects containing invalid data be created at all.
We should throw our exception in the constructor.
If the data is good, a new object is built.  If not, an exception will be thrown.</p>
<p>The Exception class contains many built-in exception types that you can use in your code.
We are going to use <code class="docutils literal notranslate"><span class="pre">ArgumentOutOfRangeException</span></code> since we want to create limitations on the range of values allowed in our program.</p>
<p><code class="docutils literal notranslate"><span class="pre">ArgumentOutOfRangeException</span></code> is its own class, so we will need to instantiate it after the keyword <code class="docutils literal notranslate"><span class="pre">throw</span></code>.
Think of it as throwing the new excpetion.
In this example, we provided our message directly as a parameter.
When the compiler encounters the exception, our message will print in the stack.
This allows the developer to see the exception, but will not print it to the console.</p>
<div class="highlight-c# notranslate"><table class="highlighttable"><tr><td class="linenos"><div class="linenodiv"><pre> 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="k">public</span> <span class="k">class</span> <span class="nc">Temperature</span>
<span class="p">{</span>
   <span class="k">public</span> <span class="k">static</span> <span class="kt">double</span> <span class="n">absoluteZero</span> <span class="p">=</span> <span class="p">-</span><span class="m">459.67</span><span class="p">;</span>

   <span class="k">public</span> <span class="nf">Temperature</span><span class="p">(</span><span class="kt">double</span> <span class="n">fahrenheit</span><span class="p">)</span>
   <span class="p">{</span>
      <span class="k">if</span><span class="p">(</span><span class="n">fahrenheit</span> <span class="p">&lt;</span> <span class="n">absoluteZero</span><span class="p">)</span>
      <span class="p">{</span>
         <span class="k">throw</span> <span class="k">new</span> <span class="nf">ArgumentOutOfRangeException</span><span class="p">(</span><span class="s">&quot;Value is below absolute zero.&quot;</span><span class="p">);</span>
      <span class="p">}</span>
      <span class="k">else</span>
      <span class="p">{</span>
         <span class="n">Console</span><span class="p">.</span><span class="n">WriteLine</span><span class="p">(</span><span class="s">&quot;You entered &quot;</span> <span class="p">+</span> <span class="n">fahrenheit</span> <span class="p">+</span> <span class="s">&quot; degrees F.&quot;</span><span class="p">);</span>
      <span class="p">}</span>
   <span class="p">}</span>
<span class="p">}</span>
</pre></div>
</td></tr></table></div>
<p><code class="docutils literal notranslate"><span class="pre">ArgumentOutOfRangeException</span></code> is not able to read your mind, you will have to provide logic that creates a reason for the exception to be thrown or not.
In this example, we created a static field <code class="docutils literal notranslate"><span class="pre">absoluteZero</span></code> to be our point of comparison.
The constructor will evaluate the validity of incoming input with an <code class="docutils literal notranslate"><span class="pre">if/else</span></code> block.</p>
<p>This example is also provided in the <code class="docutils literal notranslate"><span class="pre">Unit1-TempExceptions</span></code> project in this <a class="reference external" href="https://github.com/LaunchCodeEducation/csharp-web-dev-exceptions" target="_blank">repo<i class="fas fa-external-link-alt" aria-hidden="true"></i></a>.
Clone this repo and build along.</p>
<p>The program now provides a plan for what to do in the event that bad data is passed into a class’s field.
Imagine that a user or fellow programmer unintentionally sets a Fahrenheit value outside of the appropriate range.</p>
<p>Try this yourself to witness the breaking exception:</p>
<div class="admonition-example admonition">
<p class="first admonition-title"><i class="fas fa-binoculars" aria-hidden="true"></i>Example</p>
<p><em>Input:</em></p>
<div class="highlight-c# notranslate"><table class="highlighttable"><tr><td class="linenos"><div class="linenodiv"><pre> 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="n">Console</span><span class="p">.</span><span class="n">WriteLine</span><span class="p">(</span><span class="s">&quot;Please enter a Fahrenheit temperature value&quot;</span><span class="p">);</span>
<span class="kt">string</span> <span class="n">inputValue</span> <span class="p">=</span> <span class="n">Console</span><span class="p">.</span><span class="n">ReadLine</span><span class="p">();</span>
<span class="kt">double</span> <span class="n">inputTemp</span> <span class="p">=</span> <span class="n">Double</span><span class="p">.</span><span class="n">Parse</span><span class="p">(</span><span class="n">inputValue</span><span class="p">);</span>

<span class="c1">//Test 1: userTemp set to 73</span>
<span class="n">Temperature</span> <span class="n">userTemp</span> <span class="p">=</span> <span class="k">new</span> <span class="n">Temperature</span><span class="p">(</span><span class="n">inputTemp</span><span class="p">);</span>

<span class="c1">//re-run program</span>

<span class="c1">//Test 2: userTemp set to -8200</span>
<span class="n">Temperature</span> <span class="n">userTemp</span> <span class="p">=</span> <span class="k">new</span> <span class="n">Temperature</span><span class="p">(</span><span class="n">inputTemp</span><span class="p">);</span>
</pre></div>
</td></tr></table></div>
<p><em>Output:</em></p>
<div class="last highlight-none notranslate"><div class="highlight"><pre><span></span>//Test 1 output
You entered 73 degrees F.

//Test 2 output
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
(Parameter &#39;Value is below absolute zero&#39;) at TempsException.Temperature..ctor(Double fahrenheit)
in /Users/courtneyfrey/Projects/TempsExceptions/TempsException/TempsException/Temperature.cs:line 13
</pre></div>
</div>
</div>
<p>Above, the Temperature constructor predictably sets the Fahrenheit value of <em>Test 1</em> on <strong>Line 6</strong> and
throws an exception when provided a Fahrenheit value outside of the appropriate range with <em>Test 2</em>.
We don’t see any results of the print statement on for <em>Test 2</em> since the exception has caused the program to stop running.</p>
<p id="index-4">When we throw an exception like in the example above, we flag the anomalous circumstance. If we choose to
do nothing when the exception is thrown, the program will stop and a record of the exception
can be found in the stack trace.</p>
<p>You may also see a pop-up window telling you about the exception.</p>
<div class="figure align-default">
<a class="reference internal image-reference" href="../../_images/exception-throw-only-CSharp.png"><img alt="Screen shot of exception pop-up window" src="../../_images/exception-throw-only-CSharp.png" style="width: 684.0px; height: 240.0px;" /></a>
</div>
<p>Alternatively, we can <strong>handle</strong> an exception and offer an alternative
action, bypassing the need to stop the program. We’ll cover how to handle exceptions on the next page.</p>
<p>This is a common reason to include exception handling in your code. User input opens the door to a
variety of erroneous figures and good programs account for this uncertainty. Without exceptions in these
circumstances, a small typo could lead to any number of errors down the stack trace.</p>
</div>
<div class="section" id="when-to-use-exceptions">
<h2><span class="section-number">16.1.3. </span>When to Use Exceptions<a class="headerlink" href="#when-to-use-exceptions" title="Permalink to this headline">¶</a></h2>
<p>It is wise to use an exception if you find that there is some level of chance involved in your
program. This could be a situation where a variable is dependent on user input or a connection to
another service.</p>
<p>You may want to address those uncertainties in a different fashion. With our temperature app for example, rather than
throwing an exception, we can add a conditional statement to tell the user not to set the Fahrenheit
value to an unacceptable level. This is perfectly acceptable if the app in production allows for such a message.
As you will see on the next page, exception handling works very similarly to conditional statements like this.</p>
<p>There are many places where user-directed error messages simply won’t be appropriate. For example,
what if the value being set doesn’t come from a user but from a different method in the program? In a
situation like this, where the anomaly is not visible to the user, an exception conveys the issue to
fellow programmers who are using our codebase.</p>
<p>Or another hypothetical. What if managing the variety of errors that may arise is outside the scope of the project? In these
cases where we do not, or cannot, make up for the edge cases with coded solutions, we can throw an exception. Exceptions are an
informed way to convey the constraints of your program.</p>
</div>
<div class="section" id="check-your-understanding">
<h2><span class="section-number">16.1.4. </span>Check Your Understanding<a class="headerlink" href="#check-your-understanding" title="Permalink to this headline">¶</a></h2>
<div class="admonition-question admonition">
<p class="first admonition-title"><i class="fas fa-question" aria-hidden="true"></i>Question</p>
<p>What is the action of invoking an exception called?</p>
<ol class="last arabic simple">
<li>excepting</li>
<li>catching</li>
<li>throwing</li>
<li>handling</li>
</ol>
</div>
<div class="admonition-question admonition">
<p class="first admonition-title"><i class="fas fa-question" aria-hidden="true"></i>Question</p>
<p>True/False: Encountering an exception will always result in terminating a running program.</p>
<ol class="last arabic simple">
<li>True</li>
<li>False</li>
</ol>
</div>
</div>
</div>



    
    <nav aria-label="Next and Previous Pages">
      <ul class="pager">
        
        <li class="previous"><a href="index.html"><span aria-hidden="true">&larr;</span> <span class="section-number">16. </span>Rules to the Exceptions</a></li>
        
        
        <li class="next"><a href="handling.html"><span class="section-number">16.2. </span>Handling Exceptions <span aria-hidden="true">&rarr;</span></a></li>
        
      </ul>
    </nav>
    
    </div>
      
  </div>
</div>
<footer class="footer">
  <div class="container">
    <p class="pull-right">
      <a href="#">Back to top</a>
      
    </p>
    <p>
    </p>
  </div>
</footer>
  </body>
</html>